version: "2"

linters:
  default: all
  disable:
    - wsl
    - exhaustruct
    - forbidigo
    - gochecknoglobals
    - noinlineerr
  settings:
    staticcheck:
      checks:
        - "all"
        - "-ST1000"
        - "-ST1003"
        - "-ST1005"
    varnamelen:
      min-name-length: 3
    revive:
      rules:
        - name: exported
          severity: error
          arguments:
            - "checkPrivateReceivers"
            - "sayRepetitiveInsteadOfStutters"
        - name: package-comments
          severity: warning
    cyclop:
      max-complexity: 20
    funlen:
      lines: 120
      statements: 120
    depguard:
      rules:
        main:
          list-mode: lax
          allow:
            - $gostd
            - github.com/romantelychko/coverage-tree
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
      branch-max-lines: 2

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
    - swaggo
  settings:
    gofmt:
      simplify: true
    golines:
      max-len: 200

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
